ALTER TABLE public.extension_customizations 
ADD COLUMN popup_color_primary TEXT,
ADD COLUMN popup_color_primary_hover TEXT,
ADD COLUMN popup_color_secondary TEXT,
ADD COLUMN popup_color_bg TEXT,
ADD COLUMN popup_color_bg_elevated TEXT,
ADD COLUMN popup_color_bg_surface TEXT,
ADD COLUMN popup_color_wave_deep TEXT,
ADD COLUMN popup_color_wave_navy TEXT,
ADD COLUMN popup_color_wave_blue TEXT,
ADD COLUMN popup_color_wave_azure TEXT,
ADD COLUMN popup_color_wave_cyan TEXT,
ADD COLUMN popup_color_wave_ice TEXT,
ADD COLUMN popup_brand_kicker TEXT,
ADD COLUMN popup_brand_name TEXT,
ADD COLUMN popup_brand_badge TEXT,
ADD COLUMN popup_window_title TEXT,
ADD COLUMN popup_history_enabled BOOLEAN DEFAULT true,
ADD COLUMN popup_shortcuts JSONB,
ADD COLUMN popup_logo_rect_url TEXT,
ADD COLUMN popup_logo_square_url TEXT;